#!/usr/bin/env ruby
require 'fileutils'

def randomize_secret
  (1..40).map { |x| (65 + rand(26)).chr }.join
end

session_store_file = <<-SESSION_STORE
Rucksack::Application.config.session_store :cookie_store, :key => '_rucksack_session'
Rucksack::Application.config.secret_token = '#{randomize_secret}'
Rucksack::Application.config.secret_key_base = '#{randomize_secret}'

SESSION_STORE

def write_initializer(filename, data = nil)
  puts "adding initializer #{filename}"
  folder = "config/initializers"
  File.open("#{folder}/#{filename}", "w") { |f|; f.write(data) }
end

# copy a session store file
write_initializer("session_store.rb", session_store_file)


# Copy over example files!
Dir["config/example/*"].each do |file|
  name = "config/#{File.basename(file)}"
  unless File.exists? name
    FileUtils.cp(file, name)
    puts "Copied #{name}"
  end
end


system "bundle install"
system "rake db:rucksack:install --trace"
